import Table from "./components/Table";
import './App.css';

const driversData = [
  {
    id: 1,
    first_name: "Lonnie",
		last_name: "O' Connell ",
		email: "loconnel@gmail.com",
		gender: "Male",
		ip_address: "163.42.164.152",
		airport_code:"OGO",
		time:"7/10/2022",
		status:"TRUE",
		mobile:"707-462-9538",
		area: "9 Coleman Trail",
		show: "FALSE",
		edit: "FALSE"
  },
  {
    id: 2,
    first_name: "Lonnie",
		last_name: "O' Connell ",
		email: "loconnel@gmail.com",
		gender: "Male",
		ip_address: "163.42.164.152",
		airport_code:"OGO",
		time:"7/10/2022",
		status:"TRUE",
		mobile:"707-462-9538",
		area: "9 Coleman Trail",
		show: "FALSE",
		edit: "FALSE"
  },
  {
    id: 3,
    first_name: "Lonnie",
		last_name: "O' Connell ",
		email: "loconnel@gmail.com",
		gender: "Male",
		ip_address: "163.42.164.152",
		airport_code:"OGO",
		time:"7/10/2022",
		status:"TRUE",
		mobile:"707-462-9538",
		area: "9 Coleman Trail",
		show: "FALSE",
		edit: "FALSE"
  },
  {
    id: 4,
    first_name: "Lonnie",
		last_name: "O' Connell ",
		email: "loconnel@gmail.com",
		gender: "Male",
		ip_address: "163.42.164.152",
		airport_code:"OGO",
		time:"7/10/2022",
		status:"TRUE",
		mobile:"707-462-9538",
		area: "9 Coleman Trail",
		show: "FALSE",
		edit: "FALSE"
  },
  {
    id: 5,
		first_name: "Lonnie",
		last_name: "O' Connell ",
		email: "loconnel@gmail.com",
		gender: "Male",
		ip_address: "163.42.164.152",
		airport_code:"OGO",
		time:"7/10/2022",
		status:"TRUE",
		mobile:"707-462-9538",
		area: "9 Coleman Trail",
		show: "FALSE",
		edit: "FALSE"
  },
  {
    id: 6,
		first_name: "Lonnie",
		last_name: "O' Connell ",
		email: "loconnel@gmail.com",
		gender: "Male",
		ip_address: "163.42.164.152",
		airport_code:"OGO",
		time:"7/10/2022",
		status:"TRUE",
		mobile:"707-462-9538",
		area: "9 Coleman Trail",
		show: "FALSE",
		edit: "FALSE"
  },
  {
    id: 7,
		first_name: "Lonnie",
		last_name: "O' Connell ",
		email: "loconnel@gmail.com",
		gender: "Male",
		ip_address: "163.42.164.152",
		airport_code:"OGO",
		time:"7/10/2022",
		status:"TRUE",
		mobile:"707-462-9538",
		area: "9 Coleman Trail",
		show: "FALSE",
		edit: "FALSE"
  },
  {
    id: 8,
		first_name: "Lonnie",
		last_name: "O' Connell ",
		email: "loconnel@gmail.com",
		gender: "Male",
		ip_address: "163.42.164.152",
		airport_code:"OGO",
		time:"7/10/2022",
		status:"TRUE",
		mobile:"707-462-9538",
		area: "9 Coleman Trail",
		show: "FALSE",
		edit: "FALSE"
  },
  {
    id: 9,
		first_name: "Lonnie",
		last_name: "O' Connell ",
		email: "loconnel@gmail.com",
		gender: "Male",
		ip_address: "163.42.164.152",
		airport_code:"OGO",
		time:"7/10/2022",
		status:"TRUE",
		mobile:"707-462-9538",
		area: "9 Coleman Trail",
		show: "FALSE",
		edit: "FALSE"
  },
  {
    id: 10,
    first_name: "Lonnie",
		last_name: "O' Connell ",
		email: "loconnel@gmail.com",
		gender: "Male",
		ip_address: "163.42.164.152",
		airport_code:"OGO",
		time:"7/10/2022",
		status:"TRUE",
		mobile:"707-462-9538",
		area: "9 Coleman Trail",
		show: "FALSE",
		edit: "FALSE"
  },
  {
    id: 10,
		first_name: "Lonnie",
		last_name: "O' Connell ",
		email: "loconnel@gmail.com",
		gender: "Male",
		ip_address: "163.42.164.152",
		airport_code:"OGO",
		time:"7/10/2022",
		status:"TRUE",
		mobile:"707-462-9538",
		area: "9 Coleman Trail",
		show: "FALSE",
		edit: "FALSE"

  },
  {
    id: 11,
    first_name: "Lonnie",
		last_name: "O' Connell ",
		email: "loconnel@gmail.com",
		gender: "Male",
		ip_address: "163.42.164.152",
		airport_code:"OGO",
		time:"7/10/2022",
		status:"TRUE",
		mobile:"707-462-9538",
		area: "9 Coleman Trail",
		show: "FALSE",
		edit: "FALSE"
  },
  {
    id: 12,
    first_name: "Lonnie",
		last_name: "O' Connell ",
		email: "loconnel@gmail.com",
		gender: "Male",
		ip_address: "163.42.164.152",
		airport_code:"OGO",
		time:"7/10/2022",
		status:"TRUE",
		mobile:"707-462-9538",
		area: "9 Coleman Trail",
		show: "FALSE",
		edit: "FALSE"
  },
  {
    id: 13,
		first_name: "Lonnie",
		last_name: "O' Connell ",
		email: "loconnel@gmail.com",
		gender: "Male",
		ip_address: "163.42.164.152",
		airport_code:"OGO",
		time:"7/10/2022",
		status:"TRUE",
		mobile:"707-462-9538",
		area: "9 Coleman Trail",
		show: "FALSE",
		edit: "FALSE"
  },
  {
    id: 14,
		first_name: "Lonnie",
		last_name: "O' Connell ",
		email: "loconnel@gmail.com",
		gender: "Male",
		ip_address: "163.42.164.152",
		airport_code:"OGO",
		time:"7/10/2022",
		status:"TRUE",
		mobile:"707-462-9538",
		area: "9 Coleman Trail",
		show: "FALSE",
		edit: "FALSE"
  },
  {
    id: 15,
		first_name: "Lonnie",
		last_name: "O' Connell ",
		email: "loconnel@gmail.com",
		gender: "Male",
		ip_address: "163.42.164.152",
		airport_code:"OGO",
		time:"7/10/2022",
		status:"TRUE",
		mobile:"707-462-9538",
		area: "9 Coleman Trail",
		show: "FALSE",
		edit: "FALSE"
  },
  {
    id: 16,
		first_name: "Lonnie",
		last_name: "O' Connell ",
		email: "loconnel@gmail.com",
		gender: "Male",
		ip_address: "163.42.164.152",
		airport_code:"OGO",
		time:"7/10/2022",
		status:"TRUE",
		mobile:"707-462-9538",
		area: "9 Coleman Trail",
		show: "FALSE",
		edit: "FALSE"
  },
  {
    id: 17,
		first_name: "Lonnie",
		last_name: "O' Connell ",
		email: "loconnel@gmail.com",
		gender: "Male",
		ip_address: "163.42.164.152",
		airport_code:"OGO",
		time:"7/10/2022",
		status:"TRUE",
		mobile:"707-462-9538",
		area: "9 Coleman Trail",
		show: "FALSE",
		edit: "FALSE"
  },
  {
    id: 18,
		first_name: "Lonnie",
		last_name: "O' Connell ",
		email: "loconnel@gmail.com",
		gender: "Male",
		ip_address: "163.42.164.152",
		airport_code:"OGO",
		time:"7/10/2022",
		status:"TRUE",
		mobile:"707-462-9538",
		area: "9 Coleman Trail",
		show: "FALSE",
		edit: "FALSE"
  },
];

function App() {
  return (
    <div className="App">
			<Table 
			   data = {driversData}
			   headingColumns={["id","first_name","last_name","email","gender","ip_address","time","status","mobile","area","show","edit"]}
				 title = "Activities"
			/>
    </div>
  );
}

export default App;
